defaults:
  - datamodule: av2_simpl
  - model: simpl
  - trainer: default
  - logger: wandb
  - callbacks: default
  - optimizer: adamw
  - experiment: null
  - _self_

project_name: simpl
exp_name: debug
seed: 42
resume_from: null
output_root_dir: ./outputs/${project_name}/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}
ckpt_dir: ${output_root_dir}/ckpt

hydra:
  run:
    dir: ${output_root_dir}

trainer:
  max_epochs: 100
  overfit_batches: 1
  log_every_n_steps: 1
  detect_anomaly: true
  enable_model_summary: true

model:
  lane_net_cfg:
    dropout: 0.0
  fusion_net_cfg:
    dropout: 0.0

optimizer:
  warmup_ratio: 0.0
  lr: 1e-3
  weight_decay: 0.0

datamodule:
  num_workers: 0
  batch_size: 4
  dataset:
    preprocess: false